// Generated by gencpp from file visual_mpc_rospkg/get_action.msg
// DO NOT EDIT!


#ifndef VISUAL_MPC_ROSPKG_MESSAGE_GET_ACTION_H
#define VISUAL_MPC_ROSPKG_MESSAGE_GET_ACTION_H

#include <ros/service_traits.h>


#include <visual_mpc_rospkg/get_actionRequest.h>
#include <visual_mpc_rospkg/get_actionResponse.h>


namespace visual_mpc_rospkg
{

struct get_action
{

typedef get_actionRequest Request;
typedef get_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_action
} // namespace visual_mpc_rospkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::visual_mpc_rospkg::get_action > {
  static const char* value()
  {
    return "ed42212579cedad52c84913bafdfccf2";
  }

  static const char* value(const ::visual_mpc_rospkg::get_action&) { return value(); }
};

template<>
struct DataType< ::visual_mpc_rospkg::get_action > {
  static const char* value()
  {
    return "visual_mpc_rospkg/get_action";
  }

  static const char* value(const ::visual_mpc_rospkg::get_action&) { return value(); }
};


// service_traits::MD5Sum< ::visual_mpc_rospkg::get_actionRequest> should match 
// service_traits::MD5Sum< ::visual_mpc_rospkg::get_action > 
template<>
struct MD5Sum< ::visual_mpc_rospkg::get_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::visual_mpc_rospkg::get_action >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::get_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::visual_mpc_rospkg::get_actionRequest> should match 
// service_traits::DataType< ::visual_mpc_rospkg::get_action > 
template<>
struct DataType< ::visual_mpc_rospkg::get_actionRequest>
{
  static const char* value()
  {
    return DataType< ::visual_mpc_rospkg::get_action >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::get_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::visual_mpc_rospkg::get_actionResponse> should match 
// service_traits::MD5Sum< ::visual_mpc_rospkg::get_action > 
template<>
struct MD5Sum< ::visual_mpc_rospkg::get_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::visual_mpc_rospkg::get_action >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::get_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::visual_mpc_rospkg::get_actionResponse> should match 
// service_traits::DataType< ::visual_mpc_rospkg::get_action > 
template<>
struct DataType< ::visual_mpc_rospkg::get_actionResponse>
{
  static const char* value()
  {
    return DataType< ::visual_mpc_rospkg::get_action >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::get_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISUAL_MPC_ROSPKG_MESSAGE_GET_ACTION_H
