// Generated by gencpp from file visual_mpc_rospkg/get_actionResponse.msg
// DO NOT EDIT!


#ifndef VISUAL_MPC_ROSPKG_MESSAGE_GET_ACTIONRESPONSE_H
#define VISUAL_MPC_ROSPKG_MESSAGE_GET_ACTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visual_mpc_rospkg
{
template <class ContainerAllocator>
struct get_actionResponse_
{
  typedef get_actionResponse_<ContainerAllocator> Type;

  get_actionResponse_()
    : action()  {
      action.assign(0.0);
  }
  get_actionResponse_(const ContainerAllocator& _alloc)
    : action()  {
  (void)_alloc;
      action.assign(0.0);
  }



   typedef boost::array<float, 4>  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_actionResponse_

typedef ::visual_mpc_rospkg::get_actionResponse_<std::allocator<void> > get_actionResponse;

typedef boost::shared_ptr< ::visual_mpc_rospkg::get_actionResponse > get_actionResponsePtr;
typedef boost::shared_ptr< ::visual_mpc_rospkg::get_actionResponse const> get_actionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visual_mpc_rospkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b938d6887d09f236ab99f56a97685191";
  }

  static const char* value(const ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb938d6887d09f236ULL;
  static const uint64_t static_value2 = 0xab99f56a97685191ULL;
};

template<class ContainerAllocator>
struct DataType< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visual_mpc_rospkg/get_actionResponse";
  }

  static const char* value(const ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] action\n\
\n\
\n\
";
  }

  static const char* value(const ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_actionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visual_mpc_rospkg::get_actionResponse_<ContainerAllocator>& v)
  {
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.action[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUAL_MPC_ROSPKG_MESSAGE_GET_ACTIONRESPONSE_H
