// Generated by gencpp from file visual_mpc_rospkg/init_traj_visualmpc.msg
// DO NOT EDIT!


#ifndef VISUAL_MPC_ROSPKG_MESSAGE_INIT_TRAJ_VISUALMPC_H
#define VISUAL_MPC_ROSPKG_MESSAGE_INIT_TRAJ_VISUALMPC_H

#include <ros/service_traits.h>


#include <visual_mpc_rospkg/init_traj_visualmpcRequest.h>
#include <visual_mpc_rospkg/init_traj_visualmpcResponse.h>


namespace visual_mpc_rospkg
{

struct init_traj_visualmpc
{

typedef init_traj_visualmpcRequest Request;
typedef init_traj_visualmpcResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct init_traj_visualmpc
} // namespace visual_mpc_rospkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpc > {
  static const char* value()
  {
    return "212549b9c1a4ea535ff2ca3d14d779c5";
  }

  static const char* value(const ::visual_mpc_rospkg::init_traj_visualmpc&) { return value(); }
};

template<>
struct DataType< ::visual_mpc_rospkg::init_traj_visualmpc > {
  static const char* value()
  {
    return "visual_mpc_rospkg/init_traj_visualmpc";
  }

  static const char* value(const ::visual_mpc_rospkg::init_traj_visualmpc&) { return value(); }
};


// service_traits::MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpcRequest> should match 
// service_traits::MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpc > 
template<>
struct MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpcRequest>
{
  static const char* value()
  {
    return MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpc >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::init_traj_visualmpcRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::visual_mpc_rospkg::init_traj_visualmpcRequest> should match 
// service_traits::DataType< ::visual_mpc_rospkg::init_traj_visualmpc > 
template<>
struct DataType< ::visual_mpc_rospkg::init_traj_visualmpcRequest>
{
  static const char* value()
  {
    return DataType< ::visual_mpc_rospkg::init_traj_visualmpc >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::init_traj_visualmpcRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpcResponse> should match 
// service_traits::MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpc > 
template<>
struct MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpcResponse>
{
  static const char* value()
  {
    return MD5Sum< ::visual_mpc_rospkg::init_traj_visualmpc >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::init_traj_visualmpcResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::visual_mpc_rospkg::init_traj_visualmpcResponse> should match 
// service_traits::DataType< ::visual_mpc_rospkg::init_traj_visualmpc > 
template<>
struct DataType< ::visual_mpc_rospkg::init_traj_visualmpcResponse>
{
  static const char* value()
  {
    return DataType< ::visual_mpc_rospkg::init_traj_visualmpc >::value();
  }
  static const char* value(const ::visual_mpc_rospkg::init_traj_visualmpcResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VISUAL_MPC_ROSPKG_MESSAGE_INIT_TRAJ_VISUALMPC_H
