// Generated by gencpp from file gazebo_ext_msgs/GetCollisionNames.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETCOLLISIONNAMES_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETCOLLISIONNAMES_H

#include <ros/service_traits.h>


#include <gazebo_ext_msgs/GetCollisionNamesRequest.h>
#include <gazebo_ext_msgs/GetCollisionNamesResponse.h>


namespace gazebo_ext_msgs
{

struct GetCollisionNames
{

typedef GetCollisionNamesRequest Request;
typedef GetCollisionNamesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCollisionNames
} // namespace gazebo_ext_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ext_msgs::GetCollisionNames > {
  static const char* value()
  {
    return "440bd39ad26bc774c2ef6bcfe06d56ea";
  }

  static const char* value(const ::gazebo_ext_msgs::GetCollisionNames&) { return value(); }
};

template<>
struct DataType< ::gazebo_ext_msgs::GetCollisionNames > {
  static const char* value()
  {
    return "gazebo_ext_msgs/GetCollisionNames";
  }

  static const char* value(const ::gazebo_ext_msgs::GetCollisionNames&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ext_msgs::GetCollisionNamesRequest> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetCollisionNames > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetCollisionNamesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetCollisionNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetCollisionNamesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetCollisionNamesRequest> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetCollisionNames > 
template<>
struct DataType< ::gazebo_ext_msgs::GetCollisionNamesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetCollisionNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetCollisionNamesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ext_msgs::GetCollisionNamesResponse> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetCollisionNames > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetCollisionNamesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetCollisionNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetCollisionNamesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetCollisionNamesResponse> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetCollisionNames > 
template<>
struct DataType< ::gazebo_ext_msgs::GetCollisionNamesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetCollisionNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetCollisionNamesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETCOLLISIONNAMES_H
