// Generated by gencpp from file gazebo_ext_msgs/GetLinkVisualProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETLINKVISUALPROPERTIES_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETLINKVISUALPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_ext_msgs/GetLinkVisualPropertiesRequest.h>
#include <gazebo_ext_msgs/GetLinkVisualPropertiesResponse.h>


namespace gazebo_ext_msgs
{

struct GetLinkVisualProperties
{

typedef GetLinkVisualPropertiesRequest Request;
typedef GetLinkVisualPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLinkVisualProperties
} // namespace gazebo_ext_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ext_msgs::GetLinkVisualProperties > {
  static const char* value()
  {
    return "565eef77cf4ad97635bdc8bf4af90f87";
  }

  static const char* value(const ::gazebo_ext_msgs::GetLinkVisualProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_ext_msgs::GetLinkVisualProperties > {
  static const char* value()
  {
    return "gazebo_ext_msgs/GetLinkVisualProperties";
  }

  static const char* value(const ::gazebo_ext_msgs::GetLinkVisualProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ext_msgs::GetLinkVisualPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetLinkVisualProperties > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetLinkVisualPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetLinkVisualPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetLinkVisualPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetLinkVisualProperties > 
template<>
struct DataType< ::gazebo_ext_msgs::GetLinkVisualPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetLinkVisualPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ext_msgs::GetLinkVisualPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetLinkVisualProperties > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetLinkVisualPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetLinkVisualPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetLinkVisualPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetLinkVisualProperties > 
template<>
struct DataType< ::gazebo_ext_msgs::GetLinkVisualPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetLinkVisualPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETLINKVISUALPROPERTIES_H
