// Generated by gencpp from file gazebo_ext_msgs/GetSkyPropertiesResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETSKYPROPERTIESRESPONSE_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETSKYPROPERTIESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace gazebo_ext_msgs
{
template <class ContainerAllocator>
struct GetSkyPropertiesResponse_
{
  typedef GetSkyPropertiesResponse_<ContainerAllocator> Type;

  GetSkyPropertiesResponse_()
    : time(0.0)
    , sunrise(0.0)
    , sunset(0.0)
    , wind_speed(0.0)
    , wind_direction(0.0)
    , cloud_ambient()
    , humidity(0.0)
    , mean_cloud_size(0.0)
    , success(false)
    , status_message()  {
    }
  GetSkyPropertiesResponse_(const ContainerAllocator& _alloc)
    : time(0.0)
    , sunrise(0.0)
    , sunset(0.0)
    , wind_speed(0.0)
    , wind_direction(0.0)
    , cloud_ambient(_alloc)
    , humidity(0.0)
    , mean_cloud_size(0.0)
    , success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;

   typedef double _sunrise_type;
  _sunrise_type sunrise;

   typedef double _sunset_type;
  _sunset_type sunset;

   typedef double _wind_speed_type;
  _wind_speed_type wind_speed;

   typedef double _wind_direction_type;
  _wind_direction_type wind_direction;

   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _cloud_ambient_type;
  _cloud_ambient_type cloud_ambient;

   typedef double _humidity_type;
  _humidity_type humidity;

   typedef double _mean_cloud_size_type;
  _mean_cloud_size_type mean_cloud_size;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSkyPropertiesResponse_

typedef ::gazebo_ext_msgs::GetSkyPropertiesResponse_<std::allocator<void> > GetSkyPropertiesResponse;

typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSkyPropertiesResponse > GetSkyPropertiesResponsePtr;
typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSkyPropertiesResponse const> GetSkyPropertiesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_ext_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "785496b76654a68787d4a95f6a2d2af4";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x785496b76654a687ULL;
  static const uint64_t static_value2 = 0x87d4a95f6a2d2af4ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ext_msgs/GetSkyPropertiesResponse";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n\
float64 sunrise\n\
float64 sunset\n\
float64 wind_speed\n\
float64 wind_direction\n\
std_msgs/ColorRGBA cloud_ambient\n\
float64 humidity\n\
float64 mean_cloud_size\n\
bool success\n\
string status_message\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.sunrise);
      stream.next(m.sunset);
      stream.next(m.wind_speed);
      stream.next(m.wind_direction);
      stream.next(m.cloud_ambient);
      stream.next(m.humidity);
      stream.next(m.mean_cloud_size);
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSkyPropertiesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ext_msgs::GetSkyPropertiesResponse_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "sunrise: ";
    Printer<double>::stream(s, indent + "  ", v.sunrise);
    s << indent << "sunset: ";
    Printer<double>::stream(s, indent + "  ", v.sunset);
    s << indent << "wind_speed: ";
    Printer<double>::stream(s, indent + "  ", v.wind_speed);
    s << indent << "wind_direction: ";
    Printer<double>::stream(s, indent + "  ", v.wind_direction);
    s << indent << "cloud_ambient: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud_ambient);
    s << indent << "humidity: ";
    Printer<double>::stream(s, indent + "  ", v.humidity);
    s << indent << "mean_cloud_size: ";
    Printer<double>::stream(s, indent + "  ", v.mean_cloud_size);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETSKYPROPERTIESRESPONSE_H
