// Generated by gencpp from file gazebo_ext_msgs/GetSkyProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETSKYPROPERTIES_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETSKYPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_ext_msgs/GetSkyPropertiesRequest.h>
#include <gazebo_ext_msgs/GetSkyPropertiesResponse.h>


namespace gazebo_ext_msgs
{

struct GetSkyProperties
{

typedef GetSkyPropertiesRequest Request;
typedef GetSkyPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSkyProperties
} // namespace gazebo_ext_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ext_msgs::GetSkyProperties > {
  static const char* value()
  {
    return "785496b76654a68787d4a95f6a2d2af4";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSkyProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_ext_msgs::GetSkyProperties > {
  static const char* value()
  {
    return "gazebo_ext_msgs/GetSkyProperties";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSkyProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSkyPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSkyProperties > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetSkyPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetSkyProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSkyPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetSkyPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetSkyProperties > 
template<>
struct DataType< ::gazebo_ext_msgs::GetSkyPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetSkyProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSkyPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSkyPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSkyProperties > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetSkyPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetSkyProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSkyPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetSkyPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetSkyProperties > 
template<>
struct DataType< ::gazebo_ext_msgs::GetSkyPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetSkyProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSkyPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETSKYPROPERTIES_H
