// Generated by gencpp from file gazebo_ext_msgs/GetSurfaceParams.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMS_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMS_H

#include <ros/service_traits.h>


#include <gazebo_ext_msgs/GetSurfaceParamsRequest.h>
#include <gazebo_ext_msgs/GetSurfaceParamsResponse.h>


namespace gazebo_ext_msgs
{

struct GetSurfaceParams
{

typedef GetSurfaceParamsRequest Request;
typedef GetSurfaceParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSurfaceParams
} // namespace gazebo_ext_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ext_msgs::GetSurfaceParams > {
  static const char* value()
  {
    return "ea04093721300487c8d44a7ccf00cb51";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParams&) { return value(); }
};

template<>
struct DataType< ::gazebo_ext_msgs::GetSurfaceParams > {
  static const char* value()
  {
    return "gazebo_ext_msgs/GetSurfaceParams";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParams&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSurfaceParamsRequest> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSurfaceParams > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetSurfaceParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetSurfaceParamsRequest> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetSurfaceParams > 
template<>
struct DataType< ::gazebo_ext_msgs::GetSurfaceParamsRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSurfaceParamsResponse> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetSurfaceParams > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetSurfaceParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetSurfaceParamsResponse> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetSurfaceParams > 
template<>
struct DataType< ::gazebo_ext_msgs::GetSurfaceParamsResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMS_H
