// Generated by gencpp from file gazebo_ext_msgs/GetSurfaceParamsResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMSRESPONSE_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_ext_msgs
{
template <class ContainerAllocator>
struct GetSurfaceParamsResponse_
{
  typedef GetSurfaceParamsResponse_<ContainerAllocator> Type;

  GetSurfaceParamsResponse_()
    : elastic_modulus(0.0)
    , mu1(0.0)
    , mu2(0.0)
    , mu_torsion(0.0)
    , patch_radius(0.0)
    , poisson_ratio(0.0)
    , success(false)
    , status_message()  {
    }
  GetSurfaceParamsResponse_(const ContainerAllocator& _alloc)
    : elastic_modulus(0.0)
    , mu1(0.0)
    , mu2(0.0)
    , mu_torsion(0.0)
    , patch_radius(0.0)
    , poisson_ratio(0.0)
    , success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef double _elastic_modulus_type;
  _elastic_modulus_type elastic_modulus;

   typedef double _mu1_type;
  _mu1_type mu1;

   typedef double _mu2_type;
  _mu2_type mu2;

   typedef double _mu_torsion_type;
  _mu_torsion_type mu_torsion;

   typedef double _patch_radius_type;
  _patch_radius_type patch_radius;

   typedef double _poisson_ratio_type;
  _poisson_ratio_type poisson_ratio;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSurfaceParamsResponse_

typedef ::gazebo_ext_msgs::GetSurfaceParamsResponse_<std::allocator<void> > GetSurfaceParamsResponse;

typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsResponse > GetSurfaceParamsResponsePtr;
typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsResponse const> GetSurfaceParamsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_ext_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034c689e7f76f63e9bd3514125ee3535";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034c689e7f76f63eULL;
  static const uint64_t static_value2 = 0x9bd3514125ee3535ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ext_msgs/GetSurfaceParamsResponse";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 elastic_modulus\n\
float64 mu1\n\
float64 mu2\n\
float64 mu_torsion\n\
float64 patch_radius\n\
float64 poisson_ratio\n\
bool success\n\
string status_message\n\
";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elastic_modulus);
      stream.next(m.mu1);
      stream.next(m.mu2);
      stream.next(m.mu_torsion);
      stream.next(m.patch_radius);
      stream.next(m.poisson_ratio);
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSurfaceParamsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ext_msgs::GetSurfaceParamsResponse_<ContainerAllocator>& v)
  {
    s << indent << "elastic_modulus: ";
    Printer<double>::stream(s, indent + "  ", v.elastic_modulus);
    s << indent << "mu1: ";
    Printer<double>::stream(s, indent + "  ", v.mu1);
    s << indent << "mu2: ";
    Printer<double>::stream(s, indent + "  ", v.mu2);
    s << indent << "mu_torsion: ";
    Printer<double>::stream(s, indent + "  ", v.mu_torsion);
    s << indent << "patch_radius: ";
    Printer<double>::stream(s, indent + "  ", v.patch_radius);
    s << indent << "poisson_ratio: ";
    Printer<double>::stream(s, indent + "  ", v.poisson_ratio);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMSRESPONSE_H
