// Generated by gencpp from file gazebo_ext_msgs/GetSurfaceParamsRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMSREQUEST_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_ext_msgs
{
template <class ContainerAllocator>
struct GetSurfaceParamsRequest_
{
  typedef GetSurfaceParamsRequest_<ContainerAllocator> Type;

  GetSurfaceParamsRequest_()
    : link_collision_name()  {
    }
  GetSurfaceParamsRequest_(const ContainerAllocator& _alloc)
    : link_collision_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _link_collision_name_type;
  _link_collision_name_type link_collision_name;





  typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSurfaceParamsRequest_

typedef ::gazebo_ext_msgs::GetSurfaceParamsRequest_<std::allocator<void> > GetSurfaceParamsRequest;

typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsRequest > GetSurfaceParamsRequestPtr;
typedef boost::shared_ptr< ::gazebo_ext_msgs::GetSurfaceParamsRequest const> GetSurfaceParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_ext_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc16c45e57c83223544149fc78b39abb";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc16c45e57c83223ULL;
  static const uint64_t static_value2 = 0x544149fc78b39abbULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ext_msgs/GetSurfaceParamsRequest";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string link_collision_name\n\
";
  }

  static const char* value(const ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_collision_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSurfaceParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ext_msgs::GetSurfaceParamsRequest_<ContainerAllocator>& v)
  {
    s << indent << "link_collision_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.link_collision_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETSURFACEPARAMSREQUEST_H
