// Generated by gencpp from file gazebo_ext_msgs/GetVisualNames.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_GETVISUALNAMES_H
#define GAZEBO_EXT_MSGS_MESSAGE_GETVISUALNAMES_H

#include <ros/service_traits.h>


#include <gazebo_ext_msgs/GetVisualNamesRequest.h>
#include <gazebo_ext_msgs/GetVisualNamesResponse.h>


namespace gazebo_ext_msgs
{

struct GetVisualNames
{

typedef GetVisualNamesRequest Request;
typedef GetVisualNamesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetVisualNames
} // namespace gazebo_ext_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ext_msgs::GetVisualNames > {
  static const char* value()
  {
    return "84bee8e2f694c3877c28343b65184d47";
  }

  static const char* value(const ::gazebo_ext_msgs::GetVisualNames&) { return value(); }
};

template<>
struct DataType< ::gazebo_ext_msgs::GetVisualNames > {
  static const char* value()
  {
    return "gazebo_ext_msgs/GetVisualNames";
  }

  static const char* value(const ::gazebo_ext_msgs::GetVisualNames&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ext_msgs::GetVisualNamesRequest> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetVisualNames > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetVisualNamesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetVisualNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetVisualNamesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetVisualNamesRequest> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetVisualNames > 
template<>
struct DataType< ::gazebo_ext_msgs::GetVisualNamesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetVisualNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetVisualNamesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ext_msgs::GetVisualNamesResponse> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::GetVisualNames > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::GetVisualNamesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::GetVisualNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetVisualNamesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::GetVisualNamesResponse> should match 
// service_traits::DataType< ::gazebo_ext_msgs::GetVisualNames > 
template<>
struct DataType< ::gazebo_ext_msgs::GetVisualNamesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::GetVisualNames >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::GetVisualNamesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_GETVISUALNAMES_H
