// Generated by gencpp from file gazebo_ext_msgs/SetLinkVisualPropertiesRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_SETLINKVISUALPROPERTIESREQUEST_H
#define GAZEBO_EXT_MSGS_MESSAGE_SETLINKVISUALPROPERTIESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>
#include <std_msgs/ColorRGBA.h>
#include <std_msgs/ColorRGBA.h>
#include <std_msgs/ColorRGBA.h>

namespace gazebo_ext_msgs
{
template <class ContainerAllocator>
struct SetLinkVisualPropertiesRequest_
{
  typedef SetLinkVisualPropertiesRequest_<ContainerAllocator> Type;

  SetLinkVisualPropertiesRequest_()
    : link_visual_name()
    , ambient()
    , diffuse()
    , specular()
    , emissive()  {
    }
  SetLinkVisualPropertiesRequest_(const ContainerAllocator& _alloc)
    : link_visual_name(_alloc)
    , ambient(_alloc)
    , diffuse(_alloc)
    , specular(_alloc)
    , emissive(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _link_visual_name_type;
  _link_visual_name_type link_visual_name;

   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _ambient_type;
  _ambient_type ambient;

   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _diffuse_type;
  _diffuse_type diffuse;

   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _specular_type;
  _specular_type specular;

   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _emissive_type;
  _emissive_type emissive;





  typedef boost::shared_ptr< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLinkVisualPropertiesRequest_

typedef ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<std::allocator<void> > SetLinkVisualPropertiesRequest;

typedef boost::shared_ptr< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest > SetLinkVisualPropertiesRequestPtr;
typedef boost::shared_ptr< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest const> SetLinkVisualPropertiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_ext_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d2c0a1301a984c848faa1e2d725f0cf";
  }

  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d2c0a1301a984c8ULL;
  static const uint64_t static_value2 = 0x48faa1e2d725f0cfULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ext_msgs/SetLinkVisualPropertiesRequest";
  }

  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string link_visual_name\n\
std_msgs/ColorRGBA ambient\n\
std_msgs/ColorRGBA diffuse\n\
std_msgs/ColorRGBA specular\n\
std_msgs/ColorRGBA emissive\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.link_visual_name);
      stream.next(m.ambient);
      stream.next(m.diffuse);
      stream.next(m.specular);
      stream.next(m.emissive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLinkVisualPropertiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest_<ContainerAllocator>& v)
  {
    s << indent << "link_visual_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.link_visual_name);
    s << indent << "ambient: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.ambient);
    s << indent << "diffuse: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.diffuse);
    s << indent << "specular: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.specular);
    s << indent << "emissive: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.emissive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_SETLINKVISUALPROPERTIESREQUEST_H
