// Generated by gencpp from file gazebo_ext_msgs/SetLinkVisualProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_SETLINKVISUALPROPERTIES_H
#define GAZEBO_EXT_MSGS_MESSAGE_SETLINKVISUALPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_ext_msgs/SetLinkVisualPropertiesRequest.h>
#include <gazebo_ext_msgs/SetLinkVisualPropertiesResponse.h>


namespace gazebo_ext_msgs
{

struct SetLinkVisualProperties
{

typedef SetLinkVisualPropertiesRequest Request;
typedef SetLinkVisualPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLinkVisualProperties
} // namespace gazebo_ext_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ext_msgs::SetLinkVisualProperties > {
  static const char* value()
  {
    return "defa425a32f63c1cdc8261ea0e650ab9";
  }

  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_ext_msgs::SetLinkVisualProperties > {
  static const char* value()
  {
    return "gazebo_ext_msgs/SetLinkVisualProperties";
  }

  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::SetLinkVisualProperties > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::SetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_ext_msgs::SetLinkVisualProperties > 
template<>
struct DataType< ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::SetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ext_msgs::SetLinkVisualPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::SetLinkVisualProperties > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::SetLinkVisualPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::SetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::SetLinkVisualPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_ext_msgs::SetLinkVisualProperties > 
template<>
struct DataType< ::gazebo_ext_msgs::SetLinkVisualPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::SetLinkVisualProperties >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetLinkVisualPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_SETLINKVISUALPROPERTIES_H
