// Generated by gencpp from file gazebo_ext_msgs/SetSurfaceParams.msg
// DO NOT EDIT!


#ifndef GAZEBO_EXT_MSGS_MESSAGE_SETSURFACEPARAMS_H
#define GAZEBO_EXT_MSGS_MESSAGE_SETSURFACEPARAMS_H

#include <ros/service_traits.h>


#include <gazebo_ext_msgs/SetSurfaceParamsRequest.h>
#include <gazebo_ext_msgs/SetSurfaceParamsResponse.h>


namespace gazebo_ext_msgs
{

struct SetSurfaceParams
{

typedef SetSurfaceParamsRequest Request;
typedef SetSurfaceParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSurfaceParams
} // namespace gazebo_ext_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ext_msgs::SetSurfaceParams > {
  static const char* value()
  {
    return "5b42f161dd595c17f404172b095c2d93";
  }

  static const char* value(const ::gazebo_ext_msgs::SetSurfaceParams&) { return value(); }
};

template<>
struct DataType< ::gazebo_ext_msgs::SetSurfaceParams > {
  static const char* value()
  {
    return "gazebo_ext_msgs/SetSurfaceParams";
  }

  static const char* value(const ::gazebo_ext_msgs::SetSurfaceParams&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ext_msgs::SetSurfaceParamsRequest> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::SetSurfaceParams > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::SetSurfaceParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::SetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetSurfaceParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::SetSurfaceParamsRequest> should match 
// service_traits::DataType< ::gazebo_ext_msgs::SetSurfaceParams > 
template<>
struct DataType< ::gazebo_ext_msgs::SetSurfaceParamsRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::SetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetSurfaceParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ext_msgs::SetSurfaceParamsResponse> should match 
// service_traits::MD5Sum< ::gazebo_ext_msgs::SetSurfaceParams > 
template<>
struct MD5Sum< ::gazebo_ext_msgs::SetSurfaceParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ext_msgs::SetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetSurfaceParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ext_msgs::SetSurfaceParamsResponse> should match 
// service_traits::DataType< ::gazebo_ext_msgs::SetSurfaceParams > 
template<>
struct DataType< ::gazebo_ext_msgs::SetSurfaceParamsResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ext_msgs::SetSurfaceParams >::value();
  }
  static const char* value(const ::gazebo_ext_msgs::SetSurfaceParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_EXT_MSGS_MESSAGE_SETSURFACEPARAMS_H
