(cl:defpackage visual_mpc_rospkg-srv
  (:use )
  (:export
   "GET_ACTION"
   "<GET_ACTION-REQUEST>"
   "GET_ACTION-REQUEST"
   "<GET_ACTION-RESPONSE>"
   "GET_ACTION-RESPONSE"
   "INIT_TRAJ_VISUALMPC"
   "<INIT_TRAJ_VISUALMPC-REQUEST>"
   "INIT_TRAJ_VISUALMPC-REQUEST"
   "<INIT_TRAJ_VISUALMPC-RESPONSE>"
   "INIT_TRAJ_VISUALMPC-RESPONSE"
  ))

