// Generated by gencpp from file berkeley_sawyer/delete_traj.msg
// DO NOT EDIT!


#ifndef BERKELEY_SAWYER_MESSAGE_DELETE_TRAJ_H
#define BERKELEY_SAWYER_MESSAGE_DELETE_TRAJ_H

#include <ros/service_traits.h>


#include <berkeley_sawyer/delete_trajRequest.h>
#include <berkeley_sawyer/delete_trajResponse.h>


namespace berkeley_sawyer
{

struct delete_traj
{

typedef delete_trajRequest Request;
typedef delete_trajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct delete_traj
} // namespace berkeley_sawyer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berkeley_sawyer::delete_traj > {
  static const char* value()
  {
    return "58b1b06ba616229bc38a06a0a0af5730";
  }

  static const char* value(const ::berkeley_sawyer::delete_traj&) { return value(); }
};

template<>
struct DataType< ::berkeley_sawyer::delete_traj > {
  static const char* value()
  {
    return "berkeley_sawyer/delete_traj";
  }

  static const char* value(const ::berkeley_sawyer::delete_traj&) { return value(); }
};


// service_traits::MD5Sum< ::berkeley_sawyer::delete_trajRequest> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::delete_traj > 
template<>
struct MD5Sum< ::berkeley_sawyer::delete_trajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::delete_traj >::value();
  }
  static const char* value(const ::berkeley_sawyer::delete_trajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::delete_trajRequest> should match 
// service_traits::DataType< ::berkeley_sawyer::delete_traj > 
template<>
struct DataType< ::berkeley_sawyer::delete_trajRequest>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::delete_traj >::value();
  }
  static const char* value(const ::berkeley_sawyer::delete_trajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berkeley_sawyer::delete_trajResponse> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::delete_traj > 
template<>
struct MD5Sum< ::berkeley_sawyer::delete_trajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::delete_traj >::value();
  }
  static const char* value(const ::berkeley_sawyer::delete_trajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::delete_trajResponse> should match 
// service_traits::DataType< ::berkeley_sawyer::delete_traj > 
template<>
struct DataType< ::berkeley_sawyer::delete_trajResponse>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::delete_traj >::value();
  }
  static const char* value(const ::berkeley_sawyer::delete_trajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERKELEY_SAWYER_MESSAGE_DELETE_TRAJ_H
