// Generated by gencpp from file berkeley_sawyer/get_kinectdata.msg
// DO NOT EDIT!


#ifndef BERKELEY_SAWYER_MESSAGE_GET_KINECTDATA_H
#define BERKELEY_SAWYER_MESSAGE_GET_KINECTDATA_H

#include <ros/service_traits.h>


#include <berkeley_sawyer/get_kinectdataRequest.h>
#include <berkeley_sawyer/get_kinectdataResponse.h>


namespace berkeley_sawyer
{

struct get_kinectdata
{

typedef get_kinectdataRequest Request;
typedef get_kinectdataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_kinectdata
} // namespace berkeley_sawyer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berkeley_sawyer::get_kinectdata > {
  static const char* value()
  {
    return "b13d2865c5af2a64e6e30ab1b56e1dd5";
  }

  static const char* value(const ::berkeley_sawyer::get_kinectdata&) { return value(); }
};

template<>
struct DataType< ::berkeley_sawyer::get_kinectdata > {
  static const char* value()
  {
    return "berkeley_sawyer/get_kinectdata";
  }

  static const char* value(const ::berkeley_sawyer::get_kinectdata&) { return value(); }
};


// service_traits::MD5Sum< ::berkeley_sawyer::get_kinectdataRequest> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::get_kinectdata > 
template<>
struct MD5Sum< ::berkeley_sawyer::get_kinectdataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::get_kinectdata >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_kinectdataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::get_kinectdataRequest> should match 
// service_traits::DataType< ::berkeley_sawyer::get_kinectdata > 
template<>
struct DataType< ::berkeley_sawyer::get_kinectdataRequest>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::get_kinectdata >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_kinectdataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berkeley_sawyer::get_kinectdataResponse> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::get_kinectdata > 
template<>
struct MD5Sum< ::berkeley_sawyer::get_kinectdataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::get_kinectdata >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_kinectdataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::get_kinectdataResponse> should match 
// service_traits::DataType< ::berkeley_sawyer::get_kinectdata > 
template<>
struct DataType< ::berkeley_sawyer::get_kinectdataResponse>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::get_kinectdata >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_kinectdataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERKELEY_SAWYER_MESSAGE_GET_KINECTDATA_H
