// Generated by gencpp from file berkeley_sawyer/get_action.msg
// DO NOT EDIT!


#ifndef BERKELEY_SAWYER_MESSAGE_GET_ACTION_H
#define BERKELEY_SAWYER_MESSAGE_GET_ACTION_H

#include <ros/service_traits.h>


#include <berkeley_sawyer/get_actionRequest.h>
#include <berkeley_sawyer/get_actionResponse.h>


namespace berkeley_sawyer
{

struct get_action
{

typedef get_actionRequest Request;
typedef get_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_action
} // namespace berkeley_sawyer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berkeley_sawyer::get_action > {
  static const char* value()
  {
    return "ed42212579cedad52c84913bafdfccf2";
  }

  static const char* value(const ::berkeley_sawyer::get_action&) { return value(); }
};

template<>
struct DataType< ::berkeley_sawyer::get_action > {
  static const char* value()
  {
    return "berkeley_sawyer/get_action";
  }

  static const char* value(const ::berkeley_sawyer::get_action&) { return value(); }
};


// service_traits::MD5Sum< ::berkeley_sawyer::get_actionRequest> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::get_action > 
template<>
struct MD5Sum< ::berkeley_sawyer::get_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::get_action >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::get_actionRequest> should match 
// service_traits::DataType< ::berkeley_sawyer::get_action > 
template<>
struct DataType< ::berkeley_sawyer::get_actionRequest>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::get_action >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berkeley_sawyer::get_actionResponse> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::get_action > 
template<>
struct MD5Sum< ::berkeley_sawyer::get_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::get_action >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::get_actionResponse> should match 
// service_traits::DataType< ::berkeley_sawyer::get_action > 
template<>
struct DataType< ::berkeley_sawyer::get_actionResponse>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::get_action >::value();
  }
  static const char* value(const ::berkeley_sawyer::get_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERKELEY_SAWYER_MESSAGE_GET_ACTION_H
