// Generated by gencpp from file berkeley_sawyer/init_traj_visualmpcRequest.msg
// DO NOT EDIT!


#ifndef BERKELEY_SAWYER_MESSAGE_INIT_TRAJ_VISUALMPCREQUEST_H
#define BERKELEY_SAWYER_MESSAGE_INIT_TRAJ_VISUALMPCREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace berkeley_sawyer
{
template <class ContainerAllocator>
struct init_traj_visualmpcRequest_
{
  typedef init_traj_visualmpcRequest_<ContainerAllocator> Type;

  init_traj_visualmpcRequest_()
    : itr(0)
    , igrp(0)
    , goalmain()
    , goalaux1()
    , save_subdir()  {
    }
  init_traj_visualmpcRequest_(const ContainerAllocator& _alloc)
    : itr(0)
    , igrp(0)
    , goalmain(_alloc)
    , goalaux1(_alloc)
    , save_subdir(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _itr_type;
  _itr_type itr;

   typedef int64_t _igrp_type;
  _igrp_type igrp;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _goalmain_type;
  _goalmain_type goalmain;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _goalaux1_type;
  _goalaux1_type goalaux1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _save_subdir_type;
  _save_subdir_type save_subdir;





  typedef boost::shared_ptr< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> const> ConstPtr;

}; // struct init_traj_visualmpcRequest_

typedef ::berkeley_sawyer::init_traj_visualmpcRequest_<std::allocator<void> > init_traj_visualmpcRequest;

typedef boost::shared_ptr< ::berkeley_sawyer::init_traj_visualmpcRequest > init_traj_visualmpcRequestPtr;
typedef boost::shared_ptr< ::berkeley_sawyer::init_traj_visualmpcRequest const> init_traj_visualmpcRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace berkeley_sawyer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "212549b9c1a4ea535ff2ca3d14d779c5";
  }

  static const char* value(const ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x212549b9c1a4ea53ULL;
  static const uint64_t static_value2 = 0x5ff2ca3d14d779c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "berkeley_sawyer/init_traj_visualmpcRequest";
  }

  static const char* value(const ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 itr\n\
int64 igrp\n\
sensor_msgs/Image goalmain\n\
sensor_msgs/Image goalaux1\n\
string save_subdir\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.itr);
      stream.next(m.igrp);
      stream.next(m.goalmain);
      stream.next(m.goalaux1);
      stream.next(m.save_subdir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct init_traj_visualmpcRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::berkeley_sawyer::init_traj_visualmpcRequest_<ContainerAllocator>& v)
  {
    s << indent << "itr: ";
    Printer<int64_t>::stream(s, indent + "  ", v.itr);
    s << indent << "igrp: ";
    Printer<int64_t>::stream(s, indent + "  ", v.igrp);
    s << indent << "goalmain: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.goalmain);
    s << indent << "goalaux1: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.goalaux1);
    s << indent << "save_subdir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.save_subdir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BERKELEY_SAWYER_MESSAGE_INIT_TRAJ_VISUALMPCREQUEST_H
