// Generated by gencpp from file berkeley_sawyer/init_traj_visualmpc.msg
// DO NOT EDIT!


#ifndef BERKELEY_SAWYER_MESSAGE_INIT_TRAJ_VISUALMPC_H
#define BERKELEY_SAWYER_MESSAGE_INIT_TRAJ_VISUALMPC_H

#include <ros/service_traits.h>


#include <berkeley_sawyer/init_traj_visualmpcRequest.h>
#include <berkeley_sawyer/init_traj_visualmpcResponse.h>


namespace berkeley_sawyer
{

struct init_traj_visualmpc
{

typedef init_traj_visualmpcRequest Request;
typedef init_traj_visualmpcResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct init_traj_visualmpc
} // namespace berkeley_sawyer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berkeley_sawyer::init_traj_visualmpc > {
  static const char* value()
  {
    return "212549b9c1a4ea535ff2ca3d14d779c5";
  }

  static const char* value(const ::berkeley_sawyer::init_traj_visualmpc&) { return value(); }
};

template<>
struct DataType< ::berkeley_sawyer::init_traj_visualmpc > {
  static const char* value()
  {
    return "berkeley_sawyer/init_traj_visualmpc";
  }

  static const char* value(const ::berkeley_sawyer::init_traj_visualmpc&) { return value(); }
};


// service_traits::MD5Sum< ::berkeley_sawyer::init_traj_visualmpcRequest> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::init_traj_visualmpc > 
template<>
struct MD5Sum< ::berkeley_sawyer::init_traj_visualmpcRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::init_traj_visualmpc >::value();
  }
  static const char* value(const ::berkeley_sawyer::init_traj_visualmpcRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::init_traj_visualmpcRequest> should match 
// service_traits::DataType< ::berkeley_sawyer::init_traj_visualmpc > 
template<>
struct DataType< ::berkeley_sawyer::init_traj_visualmpcRequest>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::init_traj_visualmpc >::value();
  }
  static const char* value(const ::berkeley_sawyer::init_traj_visualmpcRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berkeley_sawyer::init_traj_visualmpcResponse> should match 
// service_traits::MD5Sum< ::berkeley_sawyer::init_traj_visualmpc > 
template<>
struct MD5Sum< ::berkeley_sawyer::init_traj_visualmpcResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berkeley_sawyer::init_traj_visualmpc >::value();
  }
  static const char* value(const ::berkeley_sawyer::init_traj_visualmpcResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berkeley_sawyer::init_traj_visualmpcResponse> should match 
// service_traits::DataType< ::berkeley_sawyer::init_traj_visualmpc > 
template<>
struct DataType< ::berkeley_sawyer::init_traj_visualmpcResponse>
{
  static const char* value()
  {
    return DataType< ::berkeley_sawyer::init_traj_visualmpc >::value();
  }
  static const char* value(const ::berkeley_sawyer::init_traj_visualmpcResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERKELEY_SAWYER_MESSAGE_INIT_TRAJ_VISUALMPC_H
