// Generated by gencpp from file berkeley_sawyer/save_kinectdataRequest.msg
// DO NOT EDIT!


#ifndef BERKELEY_SAWYER_MESSAGE_SAVE_KINECTDATAREQUEST_H
#define BERKELEY_SAWYER_MESSAGE_SAVE_KINECTDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace berkeley_sawyer
{
template <class ContainerAllocator>
struct save_kinectdataRequest_
{
  typedef save_kinectdataRequest_<ContainerAllocator> Type;

  save_kinectdataRequest_()
    : itr(0)  {
    }
  save_kinectdataRequest_(const ContainerAllocator& _alloc)
    : itr(0)  {
  (void)_alloc;
    }



   typedef int64_t _itr_type;
  _itr_type itr;





  typedef boost::shared_ptr< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct save_kinectdataRequest_

typedef ::berkeley_sawyer::save_kinectdataRequest_<std::allocator<void> > save_kinectdataRequest;

typedef boost::shared_ptr< ::berkeley_sawyer::save_kinectdataRequest > save_kinectdataRequestPtr;
typedef boost::shared_ptr< ::berkeley_sawyer::save_kinectdataRequest const> save_kinectdataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace berkeley_sawyer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36618b1eaec8d2483d42a27cb2744012";
  }

  static const char* value(const ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36618b1eaec8d248ULL;
  static const uint64_t static_value2 = 0x3d42a27cb2744012ULL;
};

template<class ContainerAllocator>
struct DataType< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "berkeley_sawyer/save_kinectdataRequest";
  }

  static const char* value(const ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 itr\n\
";
  }

  static const char* value(const ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.itr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_kinectdataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::berkeley_sawyer::save_kinectdataRequest_<ContainerAllocator>& v)
  {
    s << indent << "itr: ";
    Printer<int64_t>::stream(s, indent + "  ", v.itr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BERKELEY_SAWYER_MESSAGE_SAVE_KINECTDATAREQUEST_H
